# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Clear Table
Item.delete_all
Commodity.delete_all
Size.delete_all
Variety.delete_all

almonds = Commodity.create(description: "Almonds")
walnuts = Commodity.create(description: "Walnuts")

a16a18 = Size.create(name: "16/18")
a18a20 = Size.create(name: "18/20")
a20a22 = Size.create(name: "20/22")
a22a24 = Size.create(name: "22/24")
a23a25 = Size.create(name: "23/25")
a24a26 = Size.create(name: "24/26")
a26a28 = Size.create(name: "26/28")
a27a30 = Size.create(name: "27/30")
a30a34 = Size.create(name: "30/34")
a34a40 = Size.create(name: "34/40")
a40a50 = Size.create(name: "40/50")
a50aaos = Size.create(name: "50 AOS")
inshell = Size.create(name: "inshell")
pieces = Size.create(name: "pieces")
uns = Size.create(name: "UNS")

nonpareil = Variety.create(name: "nonpareil")
butte = Variety.create(name: "butte")
carmel = Variety.create(name: "carmel")
fritz = Variety.create(name: "fritz")
mission = Variety.create(name: "mission")
monterey = Variety.create(name: "monterey")
padre = Variety.create(name: "padre")
peerless = Variety.create(name: "peerless")
price = Variety.create(name: "price")
sonora = Variety.create(name: "sonora")

item1 = Item.create(description: "nonpareil 16/18", commodity_id: almonds.id, size_id: a16a18.id, variety_id: nonpareil.id)
item2 = Item.create(description: "nonpareil 18/20", commodity_id: almonds.id, size_id: a18a20.id, variety_id: nonpareil.id)
item3 = Item.create(description: "nonpareil 20/22", commodity_id: almonds.id, size_id: a20a22.id, variety_id: nonpareil.id)
item4 = Item.create(description: "nonpareil 22/24", commodity_id: almonds.id, size_id: a22a24.id, variety_id: nonpareil.id)
item5 = Item.create(description: "nonpareil 23/25", commodity_id: almonds.id, size_id: a23a25.id, variety_id: nonpareil.id)
item6 = Item.create(description: "nonpareil 24/26", commodity_id: almonds.id, size_id: a24a26.id, variety_id: nonpareil.id)
item7 = Item.create(description: "nonpareil 26/28", commodity_id: almonds.id, size_id: a26a28.id, variety_id: nonpareil.id)
item8 = Item.create(description: "nonpareil 27/30", commodity_id: almonds.id, size_id: a27a30.id, variety_id: nonpareil.id)
item9 = Item.create(description: "nonpareil 30/34", commodity_id: almonds.id, size_id: a30a34.id, variety_id: nonpareil.id)
item10 = Item.create(description: "nonpareil 34/40", commodity_id: almonds.id, size_id: a34a40.id, variety_id: nonpareil.id)
Item.create(description: "nonpareil 40/50", commodity_id: almonds.id, size_id: a40a50.id, variety_id: nonpareil.id)

Item.create(description: "butte 16/18", commodity_id: almonds.id, size_id: a16a18.id, variety_id: butte.id)
Item.create(description: "butte 18/20", commodity_id: almonds.id, size_id: a18a20.id, variety_id: butte.id)
Item.create(description: "butte 20/22", commodity_id: almonds.id, size_id: a20a22.id, variety_id: butte.id)
Item.create(description: "butte 22/24", commodity_id: almonds.id, size_id: a22a24.id, variety_id: butte.id)
Item.create(description: "butte 23/25", commodity_id: almonds.id, size_id: a23a25.id, variety_id: butte.id)
Item.create(description: "butte 24/26", commodity_id: almonds.id, size_id: a24a26.id, variety_id: butte.id)
Item.create(description: "butte 26/28", commodity_id: almonds.id, size_id: a26a28.id, variety_id: butte.id)
Item.create(description: "butte 27/30", commodity_id: almonds.id, size_id: a27a30.id, variety_id: butte.id)
Item.create(description: "butte 30/34", commodity_id: almonds.id, size_id: a30a34.id, variety_id: butte.id)
Item.create(description: "butte 34/40", commodity_id: almonds.id, size_id: a34a40.id, variety_id: butte.id)
Item.create(description: "butte 40/50", commodity_id: almonds.id, size_id: a40a50.id, variety_id: butte.id)

Item.create(description: "carmel 16/18", commodity_id: almonds.id, size_id: a16a18.id, variety_id: carmel.id)
Item.create(description: "carmel 18/20", commodity_id: almonds.id, size_id: a18a20.id, variety_id: carmel.id)
Item.create(description: "carmel 20/22", commodity_id: almonds.id, size_id: a20a22.id, variety_id: carmel.id)
Item.create(description: "carmel 22/24", commodity_id: almonds.id, size_id: a22a24.id, variety_id: carmel.id)
Item.create(description: "carmel 23/25", commodity_id: almonds.id, size_id: a23a25.id, variety_id: carmel.id)
Item.create(description: "carmel 24/26", commodity_id: almonds.id, size_id: a24a26.id, variety_id: carmel.id)
Item.create(description: "carmel 26/28", commodity_id: almonds.id, size_id: a26a28.id, variety_id: carmel.id)
Item.create(description: "carmel 27/30", commodity_id: almonds.id, size_id: a27a30.id, variety_id: carmel.id)
Item.create(description: "carmel 30/34", commodity_id: almonds.id, size_id: a30a34.id, variety_id: carmel.id)
Item.create(description: "carmel 34/40", commodity_id: almonds.id, size_id: a34a40.id, variety_id: carmel.id)
Item.create(description: "carmel 40/50", commodity_id: almonds.id, size_id: a40a50.id, variety_id: carmel.id)

Item.create(description: "fritz 16/18", commodity_id: almonds.id, size_id: a16a18.id, variety_id: fritz.id)
Item.create(description: "fritz 18/20", commodity_id: almonds.id, size_id: a18a20.id, variety_id: fritz.id)
Item.create(description: "fritz 20/22", commodity_id: almonds.id, size_id: a20a22.id, variety_id: fritz.id)
Item.create(description: "fritz 22/24", commodity_id: almonds.id, size_id: a22a24.id, variety_id: fritz.id)
Item.create(description: "fritz 23/25", commodity_id: almonds.id, size_id: a23a25.id, variety_id: fritz.id)
Item.create(description: "fritz 24/26", commodity_id: almonds.id, size_id: a24a26.id, variety_id: fritz.id)
Item.create(description: "fritz 26/28", commodity_id: almonds.id, size_id: a26a28.id, variety_id: fritz.id)
Item.create(description: "fritz 27/30", commodity_id: almonds.id, size_id: a27a30.id, variety_id: fritz.id)
Item.create(description: "fritz 30/34", commodity_id: almonds.id, size_id: a30a34.id, variety_id: fritz.id)
Item.create(description: "fritz 34/40", commodity_id: almonds.id, size_id: a34a40.id, variety_id: fritz.id)
Item.create(description: "fritz 40/50", commodity_id: almonds.id, size_id: a40a50.id, variety_id: fritz.id)

Item.create(description: "mission 16/18", commodity_id: almonds.id, size_id: a16a18.id, variety_id: mission.id)
Item.create(description: "mission 18/20", commodity_id: almonds.id, size_id: a18a20.id, variety_id: mission.id)
Item.create(description: "mission 20/22", commodity_id: almonds.id, size_id: a20a22.id, variety_id: mission.id)
Item.create(description: "mission 22/24", commodity_id: almonds.id, size_id: a22a24.id, variety_id: mission.id)
Item.create(description: "mission 23/25", commodity_id: almonds.id, size_id: a23a25.id, variety_id: mission.id)
Item.create(description: "mission 24/26", commodity_id: almonds.id, size_id: a24a26.id, variety_id: mission.id)
Item.create(description: "mission 26/28", commodity_id: almonds.id, size_id: a26a28.id, variety_id: mission.id)
Item.create(description: "mission 27/30", commodity_id: almonds.id, size_id: a27a30.id, variety_id: mission.id)
Item.create(description: "mission 30/34", commodity_id: almonds.id, size_id: a30a34.id, variety_id: mission.id)
Item.create(description: "mission 34/40", commodity_id: almonds.id, size_id: a34a40.id, variety_id: mission.id)
Item.create(description: "mission 40/50", commodity_id: almonds.id, size_id: a40a50.id, variety_id: mission.id)

Item.create(description: "monterey 16/18", commodity_id: almonds.id, size_id: a16a18.id, variety_id: monterey.id)
Item.create(description: "monterey 18/20", commodity_id: almonds.id, size_id: a18a20.id, variety_id: monterey.id)
Item.create(description: "monterey 20/22", commodity_id: almonds.id, size_id: a20a22.id, variety_id: monterey.id)
Item.create(description: "monterey 22/24", commodity_id: almonds.id, size_id: a22a24.id, variety_id: monterey.id)
Item.create(description: "monterey 23/25", commodity_id: almonds.id, size_id: a23a25.id, variety_id: monterey.id)
Item.create(description: "monterey 24/26", commodity_id: almonds.id, size_id: a24a26.id, variety_id: monterey.id)
Item.create(description: "monterey 26/28", commodity_id: almonds.id, size_id: a26a28.id, variety_id: monterey.id)
Item.create(description: "monterey 27/30", commodity_id: almonds.id, size_id: a27a30.id, variety_id: monterey.id)
Item.create(description: "monterey 30/34", commodity_id: almonds.id, size_id: a30a34.id, variety_id: monterey.id)
Item.create(description: "monterey 34/40", commodity_id: almonds.id, size_id: a34a40.id, variety_id: monterey.id)
Item.create(description: "monterey 40/50", commodity_id: almonds.id, size_id: a40a50.id, variety_id: monterey.id)

Item.create(description: "padre 16/18", commodity_id: almonds.id, size_id: a16a18.id, variety_id: padre.id)
Item.create(description: "padre 18/20", commodity_id: almonds.id, size_id: a18a20.id, variety_id: padre.id)
Item.create(description: "padre 20/22", commodity_id: almonds.id, size_id: a20a22.id, variety_id: padre.id)
Item.create(description: "padre 22/24", commodity_id: almonds.id, size_id: a22a24.id, variety_id: padre.id)
Item.create(description: "padre 23/25", commodity_id: almonds.id, size_id: a23a25.id, variety_id: padre.id)
Item.create(description: "padre 24/26", commodity_id: almonds.id, size_id: a24a26.id, variety_id: padre.id)
Item.create(description: "padre 26/28", commodity_id: almonds.id, size_id: a26a28.id, variety_id: padre.id)
Item.create(description: "padre 27/30", commodity_id: almonds.id, size_id: a27a30.id, variety_id: padre.id)
Item.create(description: "padre 30/34", commodity_id: almonds.id, size_id: a30a34.id, variety_id: padre.id)
Item.create(description: "padre 34/40", commodity_id: almonds.id, size_id: a34a40.id, variety_id: padre.id)
Item.create(description: "padre 40/50", commodity_id: almonds.id, size_id: a40a50.id, variety_id: padre.id)

Item.create(description: "peerless 16/18", commodity_id: almonds.id, size_id: a16a18.id, variety_id: peerless.id)
Item.create(description: "peerless 18/20", commodity_id: almonds.id, size_id: a18a20.id, variety_id: peerless.id)
Item.create(description: "peerless 20/22", commodity_id: almonds.id, size_id: a20a22.id, variety_id: peerless.id)
Item.create(description: "peerless 22/24", commodity_id: almonds.id, size_id: a22a24.id, variety_id: peerless.id)
Item.create(description: "peerless 23/25", commodity_id: almonds.id, size_id: a23a25.id, variety_id: peerless.id)
Item.create(description: "peerless 24/26", commodity_id: almonds.id, size_id: a24a26.id, variety_id: peerless.id)
Item.create(description: "peerless 26/28", commodity_id: almonds.id, size_id: a26a28.id, variety_id: peerless.id)
Item.create(description: "peerless 27/30", commodity_id: almonds.id, size_id: a27a30.id, variety_id: peerless.id)
Item.create(description: "peerless 30/34", commodity_id: almonds.id, size_id: a30a34.id, variety_id: peerless.id)
Item.create(description: "peerless 34/40", commodity_id: almonds.id, size_id: a34a40.id, variety_id: peerless.id)
Item.create(description: "peerless 40/50", commodity_id: almonds.id, size_id: a40a50.id, variety_id: peerless.id)

Item.create(description: "price 16/18", commodity_id: almonds.id, size_id: a16a18.id, variety_id: price.id)
Item.create(description: "price 18/20", commodity_id: almonds.id, size_id: a18a20.id, variety_id: price.id)
Item.create(description: "price 20/22", commodity_id: almonds.id, size_id: a20a22.id, variety_id: price.id)
Item.create(description: "price 22/24", commodity_id: almonds.id, size_id: a22a24.id, variety_id: price.id)
Item.create(description: "price 23/25", commodity_id: almonds.id, size_id: a23a25.id, variety_id: price.id)
Item.create(description: "price 24/26", commodity_id: almonds.id, size_id: a24a26.id, variety_id: price.id)
Item.create(description: "price 26/28", commodity_id: almonds.id, size_id: a26a28.id, variety_id: price.id)
Item.create(description: "price 27/30", commodity_id: almonds.id, size_id: a27a30.id, variety_id: price.id)
Item.create(description: "price 30/34", commodity_id: almonds.id, size_id: a30a34.id, variety_id: price.id)
Item.create(description: "price 34/40", commodity_id: almonds.id, size_id: a34a40.id, variety_id: price.id)
Item.create(description: "price 40/50", commodity_id: almonds.id, size_id: a40a50.id, variety_id: price.id)

Item.create(description: "sonora 16/18", commodity_id: almonds.id, size_id: a16a18.id, variety_id: sonora.id)
Item.create(description: "sonora 18/20", commodity_id: almonds.id, size_id: a18a20.id, variety_id: sonora.id)
Item.create(description: "sonora 20/22", commodity_id: almonds.id, size_id: a20a22.id, variety_id: sonora.id)
Item.create(description: "sonora 22/24", commodity_id: almonds.id, size_id: a22a24.id, variety_id: sonora.id)
Item.create(description: "sonora 23/25", commodity_id: almonds.id, size_id: a23a25.id, variety_id: sonora.id)
Item.create(description: "sonora 24/26", commodity_id: almonds.id, size_id: a24a26.id, variety_id: sonora.id)
Item.create(description: "sonora 26/28", commodity_id: almonds.id, size_id: a26a28.id, variety_id: sonora.id)
Item.create(description: "sonora 27/30", commodity_id: almonds.id, size_id: a27a30.id, variety_id: sonora.id)
Item.create(description: "sonora 30/34", commodity_id: almonds.id, size_id: a30a34.id, variety_id: sonora.id)
Item.create(description: "sonora 34/40", commodity_id: almonds.id, size_id: a34a40.id, variety_id: sonora.id)
Item.create(description: "sonora 40/50", commodity_id: almonds.id, size_id: a40a50.id, variety_id: sonora.id)






